"""empty message

Revision ID: 27f9e8d748b1
Revises: 81c2eb2f6dbe
Create Date: 2023-09-01 01:03:18.751258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27f9e8d748b1'
down_revision = '81c2eb2f6dbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('items', schema=None) as batch_op:
    #     batch_op.alter_column('price',
    #            existing_type=sa.REAL(),
    #            type_=sa.Float(precision=2),
    #            existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.create_unique_constraint("email", ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint("email", type_='unique')
        batch_op.drop_column('email')

    # with op.batch_alter_table('items', schema=None) as batch_op:
    #     batch_op.alter_column('price',
    #            existing_type=sa.Float(precision=2),
    #            type_=sa.REAL(),
    #            existing_nullable=False)

    # ### end Alembic commands ###
